{% set name = "unicorn-binance-websocket-api" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unicorn-binance-websocket-api-{{ version }}.tar.gz
  sha256: f9b360f1dcbb079c6077fa29c98d2446f335a7952574e623aa5482461a8e6542

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - cheroot
    - colorama
    - Cython
    - flask
    - flask-restful
    - lucit-licensing-python
    - psutil
    - PySocks
    - requests
    - ujson
    - unicorn-fy
    - unicorn-binance-rest-api >=1.9.0
    - websocket-client
    - websockets ==10.4
    - typing_extensions
  run:
    - cheroot
    - colorama
    - Cython
    - flask
    - flask-restful
    - lucit-licensing-python
    - psutil
    - PySocks
    - python >=3.7
    - requests
    - ujson
    - unicorn-fy
    - unicorn-binance-rest-api >=1.9.0
    - websocket-client
    - websockets ==10.4
    - typing_extensions

test:
  imports:
    - unicorn_binance_websocket_api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.lucit.tech/unicorn-binance-websocket-api.html
  summary: An unofficial Python API to use the Binance Websocket API`s.
  description: |
    An unofficial Python API to use the Binance Websocket API`s (com+testnet, com-margin+testnet, 
    com-isolated_margin+testnet, com-futures+testnet, jersey, us, dex/chain+testnet) 
    in a easy, fast, flexible, robust and fully-featured way.
  license: LSOSL
  license_file: LICENSE
  dev_url: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api
  doc_url: https://unicorn-binance-websocket-api.docs.lucit.tech

extra:
  recipe-maintainers:
    - oliver-zehentleitner
